WIP: fixing create account steps
valora-inc/wallet pull request #1162
Opened 2021-09-21 06:42 UTC by lisaqyli

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Tested

Manually tested

### Related issues

- Fixes #394

2021-09-21 08:10 UTC, lisaqyli commented
![create account name and profile](https://user-images.githubusercontent.com/3597818/134135580-3bdbe0a5-a321-4c3c-9306-cd6f9abeafd9.jpeg
![create account pincode](https://user-images.githubusercontent.com/3597818/134135588-fcf92fca-ad9b-44d8-b9d3-c4c0de6bd228.jpeg)
![restore account name and profile](https://user-images.githubusercontent.com/3597818/134135613-864ed4e8-32f7-48ca-9e91-a179ba441039.jpeg)
)

2021-09-21 20:16 UTC, tarikbellamine requested changes
Nice work!

My only issue here is that we are using both navigation props and Redux state to store the boolean value of `choseToRestoreAccount`. IMO it's unnecessary to also pass the variable through navigation props if it already exists in state.

I think a pattern that may be helpful is pulling from state then using `navigation.setParams` so that value is available in the header component. Oftentimes the best place to do this is in `componentDidMount`.

You can check out `VerificationInputScreen.tsx` as an example of how to use `navigation.setParams`

2021-09-21 20:16 UTC, tarikbellamine commented on packages/mobile/src/verify/VerificationInputScreen.tsx
> +  static navigationOptions = ({ navigation, route }: ScreenProps) => ({
I think it's unnecessary to use `route` here if you already have `chouseToRestoreAccount` in state

2021-09-22 21:17 UTC, tarikbellamine reviewed
Nice work!

2021-09-22 21:17 UTC, tarikbellamine commented on packages/mobile/src/verify/VerificationEducationScreen.tsx
> +  useEffect(() => {
Nice!

2021-09-22 21:17 UTC, tarikbellamine commented on packages/mobile/src/verify/VerificationLoadingScreen.tsx
> +    choseToRestoreAccount: state.account.choseToRestoreAccount,
I don't think we need any changes to this file anymore :)

2021-09-22 22:40 UTC, tarikbellamine approved these changes
🔥

2021-09-22 23:00 UTC, merged

2021-09-29 10:50 UTC, ValoraQA commented
Hey @MuckT , We have verified this task using Latest Android Internal build V1.20.2, Test flight build 1.20.2 (1632859153) & updated the status in Test Quality Tools.

**Android(10):**
Case1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516235
Case2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516236

**iOS (14):**
Case1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516251
Case2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516252

**Devices:** iPhone 12 (14.7.1), Redmi Note 8 (10.0)

2021-09-29 10:50 UTC, ValoraQA commented
Hi @MuckT  we have verified this issue on latest Android internal build V1.20.2 and updated the status in Testquality tool link .
**Test Qulaity tool link :**
**Link 1 :** https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516235
**Link 2 :** https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516236

**Verified On Devices:** Redmi Note 8 (9.0)

CC: @lisaqyli

2021-09-30 08:33 UTC, ValoraQA commented
Hey @MuckT , We have verified this issue using Latest Android Internal build V1.20.2 & Test flight build 1.20.2 (1632859153) & updated the status in Test Quality Tool.
Test Quality Tool Link:

Android(11):
Case 1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516231
Case 2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516232

Android (8):
Case 1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516243
Case 2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516244

Verified on Devices : OnePlus 7T (11.0) , Samsung Galaxy J5 (8.0)
CC: @lisaqyli

2021-10-01 13:47 UTC, ValoraQA commented
Hey @MuckT , We have verified this issue using Latest  Test flight build 1.20.2 (1632859153) & updated the status in Test Quality Tool.
**Test Quality Tool Link:**
**iOS(13.0)**
- https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516247
**Verified On Devices:** iPhone Xs Max(13.5.1)

2021-10-04 06:53 UTC, ValoraQA commented
Hey @MuckT , We have verified this issue using Latest Test flight build 1.20.2 (1632859153) & updated the status in Test Quality Tool.
Test Quality Tool Link:
**iOS(15.0):**
**Case1:** https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516255
**Case2:** https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516256

**Devices:** iPhone 12(15.0)
CC: @lisaqyli